remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [JSON Processing (JSON-P)]
description: [API and Reference Implementation (RI) of JSR-374]

links:
  source: https://github.com/eclipse-ee4j/jsonp
  #docs: documentation
  javadocs: 
    API: docs/api/?overview-summary.html
    RI: docs/impl/?overview-summary.html
  download: https://github.com/eclipse-ee4j/jsonp/releases
  mailinglist: https://accounts.eclipse.org/mailing-list/jsonp-dev
  #faq: FAQ
